/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.preprocess.forms;

import br.preprocess.App;
import br.preprocess.core.Chart;
import br.preprocess.core.Dataset;
import br.preprocess.core.KNearestNeighbour;
import br.preprocess.core.LinearDiscriminantAnalysis;
import br.preprocess.utils.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class ReducaoLDA extends javax.swing.JDialog {

    private final App parent;
    private final Chart ch;
    private final Dataset ds;
    private final LinearDiscriminantAnalysis lda;
    private final KNearestNeighbour knn;
    
    /**
     * Creates new form WindowModel
     * @param parent
     * @param modal
     */
    public ReducaoLDA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (App) parent;
        this.setLocation(parent.getLocation());
        this.ch = new Chart(this.redChart.getWidth(), this.redChart.getHeight(),
                    "LDA - Desempenho", "Taxa de Redução", "Taxa de Acerto", Chart.CHART_LINE, true);
        this.ch.addXYSerie("Redução");
        Utils.addPlot(this.redChart, ch);
        this.ds = this.parent.getDsManipulavel().clonar();
        this.knn = this.parent.getKnn();
        this.lda = new LinearDiscriminantAnalysis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        redChart = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        redLimiar = new javax.swing.JSpinner();
        redPrev = new javax.swing.JButton();
        redAplic = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        redStats = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Linear Discriminant Analysis (LDA)");
        setIconImage(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        redChart.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout redChartLayout = new javax.swing.GroupLayout(redChart);
        redChart.setLayout(redChartLayout);
        redChartLayout.setHorizontalGroup(
            redChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        redChartLayout.setVerticalGroup(
            redChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração"));

        jLabel2.setText("<html>\n<p>\nA avaliação de desempenho será realizada através do <strong>k-NN</strong> com a <strong>configuração atual</strong>.\n</p>\n<p>\n*A base de dados será automaticamente normalizada, caso ainda não seja.\n</p>\n</html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Limiar de redução:");

        redLimiar.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 0.9d, 0.1d));

        redPrev.setText("Pré-visualizar");
        redPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redPrevActionPerformed(evt);
            }
        });

        redAplic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        redAplic.setText("Aplicar Redução*");
        redAplic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redAplicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redLimiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(redPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redAplic, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(redLimiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redPrev)
                    .addComponent(redAplic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        redStats.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        redStats.setFocusable(false);
        jScrollPane2.setViewportView(redStats);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redPrevActionPerformed
        double split = this.parent.getSplitRatio();
        double threshold = (double) this.redLimiar.getValue();
        double no_reduct = 0, best_pct = 0, best_lim = threshold;
        this.ch.clear();
        for (double i = 0; i <= threshold; i+= 0.1) {
            this.lda.setDataset(this.ds.clonar());
            this.lda.setRatio(i);
            this.lda.reduceDataset();
            this.knn.setDataset(this.lda.getDataset(), split);
            if (this.knn.execute()) {
                if (this.knn.getEvl().pctCorrect()/100 >= best_pct && i != 0) {
                    best_pct = this.knn.getEvl().pctCorrect()/100;
                    best_lim = i;
                }
                if (i == 0) no_reduct = this.knn.getEvl().pctCorrect()/100;
            }
            this.ch.update(i, this.knn.getEvl().pctCorrect()/100, 0);
        }
        this.redLimiar.setValue(best_lim);
        this.redStats.setText("(k-NN) Sem redução: "+no_reduct
                +"\n(k-NN) Com redução: "+best_pct+"\n\n"+this.lda.getInfo());
        Utils.addPlot(this.redChart, this.ch);
    }//GEN-LAST:event_redPrevActionPerformed

    private void redAplicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redAplicActionPerformed
        if (this.lda.getDataset() != null) {
            this.lda.setRatio((double) this.redLimiar.getValue());
            this.lda.setDataset(this.ds.clonar());
            if (this.lda.reduceDataset()) {
                this.parent.insertLog("Aplicou redução com LDA na base de dados "+this.ds.getDatasetName());
                this.parent.setDsManipulavel(this.lda.getDataset());
                this.parent.updateAll();
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Somente é possível aplicar LDA se pré-visualizar os resultados antes.");
        }
    }//GEN-LAST:event_redAplicActionPerformed
   
    public void open() {
        this.setVisible(true);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton redAplic;
    private javax.swing.JPanel redChart;
    private javax.swing.JSpinner redLimiar;
    private javax.swing.JButton redPrev;
    private javax.swing.JTextPane redStats;
    // End of variables declaration//GEN-END:variables
}
